spring:
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/singers_contests?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    restart:
      enabled: true

# setup tomcat do not limit form post file size
server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  port: ${PORT:8080}


app:
  default:
    admin:
      password: P@ssw0rd

mail:
  host: "localhost"
  port: 65000
  username: "office@singerscontests.bg"
  password: ""
  sender: "office@singerscontests.bg"
  admin: "office@singerscontests.bg"
  registration_mail_subject: "You have registered in Singers Contest System!"
  change_mail_subject: "You have change you email in Singers Contest System!"
  performance_issue_mail_subject: "There was an performance issue!"

cloudinary:
  cloud_name: "dsylyy9iz"
  api_key: "358932685941447"
  api_secret: "joJrEUgJxd-F1pCI_1wj1txA8cs"
  secure: true,
  override: true

logging:
  level:
    root: info

#  make it false to stop overload of scenario order every time when you restart
seed:
  init_scenario: true

max_execution_time: 500
